# -*- coding: utf-8 -*-
"""clusteringch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YTf1GPDAPySh1Il8fHMzOW7nszPbCnUd
"""

import pandas as pd
import matplotlib.pyplot as plt
from scipy.cluster.hierarchy import linkage, dendrogram, fcluster

from google.colab import drive
drive.mount('/content/drive')

#pathとカラムは確定次第修正
def clustering_ch(path,sheet_name):
  path_nirs = path
  nirs_raw = pd.read_excel(path_nirs,index_col=1,sheet_name=sheet_name)
  nirs_trim = nirs_raw.iloc[0:1735, 1:16]
  nirs=nirs_trim.transpose()
  #ウォード法によるクラスタリング
  linkage_result = linkage(nirs, method='ward', metric='euclidean')
  plt.figure(num=None, figsize=(16, 9), facecolor='white', edgecolor='black')
  dendrogram(linkage_result, labels=nirs.index)
  plt.show()

for i in range(1,13):
  clusteringch('file.xlsx',i)
  print('--------' + str(i) +'--------' )

#pathとカラムは確定次第修正
def clustering_ch(path,sheet_name):
  path_nirs = path
  nirs_raw = pd.read_excel(path_nirs,index_col=1,sheet_name=sheet_name)
  nirs_trim = nirs_raw.iloc[1247:1735, 1:16]
  nirs=nirs_trim.transpose()
  #ウォード法によるクラスタリング
  linkage_result = linkage(nirs, method='ward', metric='euclidean')
  plt.figure(num=None, figsize=(16, 9), facecolor='white', edgecolor='black')
  dendrogram(linkage_result, labels=nirs.index)
  plt.show()

for i in range(1,13):
  clustering_ch('file.xlsx',i)
  print('--------' + str(i) +'--------' )